name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install backend
        run: npm ci
        working-directory: backend
      - name: Install frontend
        run: npm ci
        working-directory: frontend
      - name: Run tests
        run: npm run test
      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: frontend
      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: railwayapp/cli-action@v1.2.7
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          command: up --environment production --service ${{ secrets.RAILWAY_SERVICE_ID }}
          cwd: backend
